repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-json
      - id: check-xml
      - id: mixed-line-ending
      - id: pretty-format-json
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.12.0
    hooks:
      - id: pretty-format-java
        args: [--autofix]

  - repo: https://github.com/ejba/pre-commit-maven
    rev: v0.3.4
    hooks:
      - id: maven
        args: ["clean compile"]

  # - repo: local
  #   hooks:
  #     - id: unit-test
  #       name: unit-test
  #       entry: bash unit-test.sh
  #       language: system
  #       verbose: true
